/* ==========================================================================
   CORE  —  application state, navigation and the helpers every module shares.

   Carried over from ADT_Revamp unchanged in spirit: state lives in module
   globals, pages are pure builders returning markup, and nothing here touches
   the DOM except the shell itself.
   ========================================================================== */

/* ── State ──────────────────────────────────────────────────────────────── */
let page = 'dashboard';
let activeSidebarItem = 'dashboard';
let sidebarCollapsed = false;
let openDropdowns = new Set();

/* ── Text helpers ───────────────────────────────────────────────────────── */
function esc(v) {
  return String(v == null ? '' : v)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
function attrSafe(v) {
  return String(v == null ? '' : v).replace(/&/g, '&amp;').replace(/"/g, '&quot;');
}
function statusClass(v) {
  return String(v).toLowerCase().replace(/[^a-z0-9]+/g, '-');
}

/* ── Numbers ────────────────────────────────────────────────────────────────
   Quantities carry three decimals because the BRD's own documents do
   (258.000 KG), and a BOM-ratio consumption has to be shown at the configured
   precision rather than rounded to look tidy. */
function fmtQty(n, dp) {
  if (n == null || n === '') return '';
  return Number(n).toLocaleString('en-IN', {
    minimumFractionDigits: dp == null ? 3 : dp,
    maximumFractionDigits: dp == null ? 3 : dp
  });
}
function fmtMoney(n) {
  if (n == null || n === '') return '';
  return '₹ ' + Number(n).toLocaleString('en-IN', { minimumFractionDigits: 0, maximumFractionDigits: 2 });
}

/* F30 · ONE DATE FORMAT.
   Dates arrive from two places — typed into a date input (ISO, "2026-10-02")
   and generated by stampNow ("8 Oct 2026") — and both were being printed raw,
   so two formats sat on the same row. Everything renders through here. */
const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
function fmtDate(v) {
  if (!v) return '';
  const s = String(v);
  const m = s.match(/^(\d{4})-(\d{2})-(\d{2})/);
  if (!m) return s;                                  /* already display form */
  return Number(m[3]) + ' ' + MONTHS[Number(m[2]) - 1] + ' ' + m[1];
}

/* ── Status tones ───────────────────────────────────────────────────────────
   ONE MEANING PER HUE, straight from the ADT token contract:
     ok    settled + positive      wait  still in flight
     bad   settled + negative      info  purely informational
     idle  no longer in play

   Amber is "waiting", never "bad" — which is why Returned and Short-Closed are
   amber (someone still has to act) while Rejected and Cancelled are red (the
   record has stopped).  Voided is idle, not red: nothing failed, the document
   simply no longer applies. */
const STATUS_TONE = {
  /* Deal */
  'created': 'info', 'sent-for-approval': 'wait', 'returned': 'wait',
  'modified': 'wait', 'approved': 'ok', 'rejected': 'bad', 'closed': 'idle',
  /* Order */
  'draft': 'idle', 'short-closed': 'wait',
  /* Shipment */
  'not-raised': 'idle', 'freezed-outbound-release': 'wait',
  'challan-generated': 'wait', 'gate-cleared': 'ok', 'cancelled': 'bad',
  /* Stage */
  'in-progress': 'wait', 'completed': 'ok',
  /* Delivery Note */
  'generated': 'info', 'voided': 'idle',
  /* Challan */
  'overdue': 'bad',
  /* IMR */
  'confirmed': 'ok',
  /* Material position */
  'available': 'ok', 'reserved': 'wait', 'at-vendor-in-transit': 'info',
  'returned-to-store': 'ok',
  /* Line status */
  'open': 'info', 'partially-received': 'wait', 'fully-received': 'ok',
  /* Master records */
  'active': 'ok', 'inactive': 'idle'
};
function statusTone(v) { return STATUS_TONE[statusClass(v)] || 'idle'; }

/* Display names for statuses whose BRD term misleads or overflows a pill.
   "Freezed Outbound Release" reads as held/blocked — the opposite of what
   happened — and was being amputated mid-word in narrow columns. The BRD term
   stays in the tooltip so an auditor can match the document. */
const STATUS_DISPLAY = {
  'Freezed Outbound Release': 'Released to dispatch',
  'Challan Generated': 'Challan raised',
  'Sent for Approval': 'Awaiting approval'
};

/* A status badge.  PILL shape, always — the shape system says a pill is a
   read-only state and is never clickable.  Never build one by hand. */
function sbStatus(value, label) {
  if (!value) return '';
  const shown = label || STATUS_DISPLAY[value] || value;
  const tip = (!label && STATUS_DISPLAY[value]) ? ' title="' + attrSafe(value) + '"' : '';
  return '<span class="sb-st sb-st-' + statusTone(value) + '"' + tip + '>' + esc(shown) + '</span>';
}

/* ── Icons ──────────────────────────────────────────────────────────────── */
const ico = {
  grid:     '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/></svg>',
  fileText: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="8" y1="13" x2="16" y2="13"/><line x1="8" y1="17" x2="12" y2="17"/></svg>',
  fileCheck:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><path d="M9 15l2 2 4-4"/></svg>',
  cart:     '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="9" cy="20" r="1.5"/><circle cx="18" cy="20" r="1.5"/><path d="M2 3h3l2.4 12.4a2 2 0 0 0 2 1.6h8.2a2 2 0 0 0 2-1.6L21.5 7H6"/></svg>',
  truck:    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="1" y="6" width="13" height="11" rx="1.5"/><path d="M14 10h4l3 3.5V17h-7z"/><circle cx="6" cy="19" r="1.8"/><circle cx="18" cy="19" r="1.8"/></svg>',
  layers:   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><polygon points="12 2 22 8 12 14 2 8"/><polyline points="2 14 12 20 22 14"/></svg>',
  box:      '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M21 8l-9-5-9 5v8l9 5 9-5z"/><polyline points="3 8 12 13 21 8"/><line x1="12" y1="13" x2="12" y2="21"/></svg>',
  inbox:    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><polyline points="21 13 15 13 13 16 11 16 9 13 3 13"/><path d="M5 5h14l2 8v6a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-6z"/></svg>',
  upload:   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 16v3a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-3"/><polyline points="8 8 12 4 16 8"/><line x1="12" y1="4" x2="12" y2="15"/></svg>',
  shield:   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><path d="M9 12l2 2 4-4"/></svg>',
  scale:    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><line x1="12" y1="3" x2="12" y2="21"/><path d="M6 7l-3 7h6z"/><path d="M18 7l-3 7h6z"/><line x1="4" y1="21" x2="20" y2="21"/><line x1="5" y1="7" x2="19" y2="7"/></svg>',
  database: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M21 12c0 1.66-4 3-9 3s-9-1.34-9-3"/><path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5"/></svg>',
  tag:      '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M20.6 13.4L12 22l-9-9V3h10l7.6 7.6a2 2 0 0 1 0 2.8z"/><circle cx="7.5" cy="7.5" r="1.5"/></svg>',
  building: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M3 21h18"/><path d="M5 21V7l7-4 7 4v14"/><path d="M9 21v-5h6v5"/><path d="M9 10h.01"/><path d="M15 10h.01"/></svg>',
  users:    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>',
  userCheck:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><polyline points="16 11 18 13 22 9"/></svg>',
  bell:     '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/></svg>',
  cog:      '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09a1.65 1.65 0 0 0-1-1.51 1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09a1.65 1.65 0 0 0 1.51-1 1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg>',
  chart:    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><line x1="3" y1="21" x2="21" y2="21"/><rect x="5" y="11" width="3.6" height="8"/><rect x="10.2" y="6" width="3.6" height="13"/><rect x="15.4" y="14" width="3.6" height="5"/></svg>',
  history:  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M3 12a9 9 0 1 0 3-6.7L3 8"/><polyline points="3 3 3 8 8 8"/><polyline points="12 7 12 12 15.5 14"/></svg>',
  sliders:  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><line x1="4" y1="21" x2="4" y2="14"/><line x1="4" y1="10" x2="4" y2="3"/><line x1="12" y1="21" x2="12" y2="12"/><line x1="12" y1="8" x2="12" y2="3"/><line x1="20" y1="21" x2="20" y2="16"/><line x1="20" y1="12" x2="20" y2="3"/><line x1="1" y1="14" x2="7" y2="14"/><line x1="9" y1="8" x2="15" y2="8"/><line x1="17" y1="16" x2="23" y2="16"/></svg>',
  receipt:  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 2v20l2-1 2 1 2-1 2 1 2-1 2 1 2-1V2l-2 1-2-1-2 1-2-1-2 1-2-1z"/><line x1="8" y1="7" x2="16" y2="7"/><line x1="8" y1="11" x2="16" y2="11"/><line x1="8" y1="15" x2="13" y2="15"/></svg>'
};

/* ── Navigation ─────────────────────────────────────────────────────────────
   Grouped by what the user is doing, not by which team owns the screen — the
   ADT rule.  A section earns its place only if it holds more than one module,
   a dropdown only if it holds more than one page, and a child never repeats
   the word its parent already said. */
const SIDEBAR = [
  { section: 'Overview' },
  { id: 'dashboard', label: 'Dashboard', icon: ico.grid },

  { section: 'Sub-Contracting' },
  { id: 'scr',       label: 'Requests',  icon: ico.fileText },
  { id: 'orders',    label: 'Orders',    icon: ico.cart },
  { id: 'shipments', label: 'Shipments', icon: ico.box },

  { section: 'Fulfilment' },
  { id: 'allocation', label: 'Material Allocation', icon: ico.layers },
  { dropdown: 'Stores', icon: ico.inbox, children: [
      { id: 'outbound', label: 'Outbound', icon: ico.upload },
      { id: 'inward',   label: 'Inward',   icon: ico.inbox }
  ]},
  { id: 'logistics', label: 'Logistics',   icon: ico.truck },
  { id: 'gate',      label: 'Gate Outward', icon: ico.shield },
  { dropdown: 'Documents', icon: ico.fileCheck, children: [
      { id: 'delivery-notes', label: 'Delivery Notes', icon: ico.fileCheck },
      { id: 'challans',       label: 'Challans',       icon: ico.receipt }
  ]},
  { id: 'reconciliation', label: 'Reconciliation', icon: ico.scale },

  { section: 'Configuration' },
  { dropdown: 'Masters', icon: ico.database, children: [
      { id: 'products',         label: 'Products',          icon: ico.box },
      { id: 'plants',           label: 'Plants & Locations', icon: ico.building },
      { id: 'vendors',          label: 'Vendors',           icon: ico.users },
      { id: 'rate-contracts',   label: 'Rate Contracts',    icon: ico.fileText },
      { id: 'purchase-offices', label: 'Purchase Offices',  icon: ico.cart },
      { id: 'reason-codes',     label: 'Reason Codes',      icon: ico.tag },
      { id: 'parameters',       label: 'Parameters',        icon: ico.sliders }
  ]},
  { dropdown: 'Administration', icon: ico.cog, children: [
      { id: 'teams',         label: 'Teams',         icon: ico.users },
      { id: 'staff-roles',   label: 'Staff & Roles', icon: ico.userCheck },
      { id: 'notifications', label: 'Notifications', icon: ico.bell }
  ]},

  { section: 'Insights' },
  { id: 'reports',  label: 'Reports',      icon: ico.chart },
  { id: 'activity', label: 'Activity Log', icon: ico.history }
];

function getSidebarItems() { return SIDEBAR; }

/* Page titles.  Also the single source for the topbar heading. */
const PAGE_TITLE = {
  dashboard: 'Dashboard', scr: 'Sub-Contracting Requests', orders: 'Sub-Contracting Orders',
  shipments: 'Shipments', allocation: 'Material Allocation', outbound: 'Stores Outbound',
  inward: 'Stores Inward', logistics: 'Logistics', gate: 'Gate Outward',
  'delivery-notes': 'Delivery Notes', challans: 'Challans', reconciliation: 'Reconciliation',
  products: 'Product Master', plants: 'Plants & Storage Locations', vendors: 'Vendor Master',
  'rate-contracts': 'Rate Contracts', 'purchase-offices': 'Purchase Offices & Number Series',
  'reason-codes': 'Reason Codes', parameters: 'Sub-Contracting Parameters',
  teams: 'Teams', 'staff-roles': 'Staff & Roles', notifications: 'Notification Events',
  reports: 'Reports', activity: 'Activity Log'
};
function getPageTitle(pg) { return PAGE_TITLE[pg] || pg; }

/* ── Sidebar ────────────────────────────────────────────────────────────────
   Rebuilt only when its signature changes, so a page repaint never disturbs an
   open dropdown.  Permission filtering happens HERE rather than at render
   time: a nav item you cannot open should not be visible at all, and a section
   or dropdown left empty by the filter removes itself with it. */
function sidebarSig() {
  return currentUserId + '|' + (sidebarCollapsed ? 1 : 0) + '|' + activeSidebarItem +
         '|' + Array.from(openDropdowns).sort().join(',');
}
let lastSidebarSig = null;

/* F33 · openDropdowns was only ever written by a click, so ANY other route to
   a child page — a deep link, a role switch, a redirect after an action — left
   the owning dropdown shut and the active item nowhere on screen. */
function expandOwningDropdown(pageId) {
  SIDEBAR.forEach(item => {
    if (item.dropdown && (item.children || []).some(c => c.id === pageId))
      openDropdowns.add(item.dropdown);
  });
}

function visibleChildren(item) {
  return (item.children || []).filter(c => can(c.id, 'v'));
}

function buildSidebar() {
  const el = document.getElementById('sidebar');
  if (!el) return;
  lastSidebarSig = sidebarSig();
  el.className = 'sidebar' + (sidebarCollapsed ? ' collapsed' : '');
  el.innerHTML = '';

  /* The product names itself in its own chrome. A sidebar starting with the
     word "MENU" is template furniture; this is where the module identity and
     the plant you are operating live. */
  const top = document.createElement('div');
  top.className = 'sb-top';
  top.innerHTML = (sidebarCollapsed ? '' :
      '<div class="sb-brand"><span class="sb-brand-name">Sub-Contracting</span>' +
      '<span class="sb-brand-sub">L&amp;T Trichy Works</span></div>') +
    '<button class="sidebar-toggle" onclick="toggleSidebar()" title="Toggle sidebar" aria-label="Toggle sidebar">' +
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="4" y="5" width="16" height="14" rx="2"/><line x1="15" y1="5" x2="15" y2="19"/></svg></button>';
  el.appendChild(top);

  /* A section header is held back until something under it survives the
     filter, so it can never be emitted above an empty stretch of nav. */
  let pendingSection = null;

  SIDEBAR.forEach(item => {
    if (item.section) { pendingSection = item.section; return; }

    const kids = item.dropdown ? visibleChildren(item) : null;
    if (item.dropdown ? !kids.length : !can(item.id, 'v')) return;

    if (pendingSection && !sidebarCollapsed) {
      const s = document.createElement('div');
      s.className = 'sb-section';
      s.textContent = pendingSection;
      el.appendChild(s);
    }
    pendingSection = null;

    if (item.dropdown) {
      const isOpen = openDropdowns.has(item.dropdown);
      const hasActive = kids.some(c => c.id === activeSidebarItem);
      if (!sidebarCollapsed) {
        const parent = document.createElement('button');
        parent.type = 'button';
        parent.className = 'sb-parent' + (isOpen ? ' open' : '') + (hasActive ? ' has-active' : '');
        parent.title = item.dropdown;
        parent.innerHTML = '<div class="sb-ico-wrap">' + (item.icon || '') + '</div><span>' + esc(item.dropdown) + '</span>' +
          '<svg class="sb-chev" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="6 9 12 15 18 9"/></svg>';

        const box = document.createElement('div');
        box.className = 'sb-children';
        box.style.maxHeight = isOpen ? '600px' : '0';
        kids.forEach(child => {
          const b = document.createElement('button');
          b.type = 'button';
          b.className = 'sb-item' + (child.id === activeSidebarItem ? ' active' : '');
          b.title = child.label;
          b.innerHTML = '<div class="sb-ico-wrap">' + (child.icon || '') + '</div><span>' + esc(child.label) + '</span>';
          b.onclick = () => navigatePage(child.id);
          box.appendChild(b);
        });
        parent.onclick = () => {
          if (openDropdowns.has(item.dropdown)) {
            openDropdowns.delete(item.dropdown);
            box.style.maxHeight = '0';
            parent.classList.remove('open');
          } else {
            el.querySelectorAll('.sb-parent.open').forEach(p => p.classList.remove('open'));
            el.querySelectorAll('.sb-children').forEach(c => c.style.maxHeight = '0');
            openDropdowns.clear();
            openDropdowns.add(item.dropdown);
            box.style.maxHeight = '600px';
            parent.classList.add('open');
          }
        };
        el.appendChild(parent);
        el.appendChild(box);
      } else {
        const d = document.createElement('button');
        d.type = 'button';
        d.className = 'sb-parent' + (hasActive ? ' has-active' : '');
        d.title = item.dropdown;
        d.innerHTML = '<div class="sb-ico-wrap">' + (item.icon || '') + '</div>';
        d.onclick = () => {
          sidebarCollapsed = false;
          openDropdowns.clear();
          openDropdowns.add(item.dropdown);
          buildSidebar();
        };
        el.appendChild(d);
      }
      return;
    }

    const b = document.createElement('button');
    b.type = 'button';
    b.className = 'sb-item' + (item.id === activeSidebarItem ? ' active' : '');
    b.title = item.label;
    b.innerHTML = '<div class="sb-ico-wrap">' + (item.icon || '') + '</div><span>' + esc(item.label) + '</span>';
    b.onclick = () => navigatePage(item.id);
    el.appendChild(b);
  });
}

function toggleSidebar() {
  sidebarCollapsed = !sidebarCollapsed;
  if (sidebarCollapsed) openDropdowns.clear();
  buildSidebar();
}

/* The address bar follows you. Without this, copying the URL to share "the
   challan we're arguing about" silently shared your dashboard — the app read
   ?page=&open= inbound but never wrote them. */
let lastOpenedRecord = null;
function syncUrl() {
  try {
    const q = '?as=' + currentUserId + '&page=' + page + '&view=' + channel +
              (lastOpenedRecord ? '&open=' + lastOpenedRecord : '');
    history.replaceState(null, '', q);
  } catch (e) { /* file:// in some browsers refuses replaceState — fine */ }
}

/* `withFilter` lands the user on a PRE-FILTERED queue. A dashboard tile that
   says "Requests to approve · 1" and then opens the full nine-row list with
   the filter on All was promising a queue and delivering a haystack. */
function navigatePage(pg, withFilter) {
  if (!can(pg, 'v')) return;
  /* Leaving an open request form used to silently empty everything typed —
     the form re-rendered from a stale draft while still LOOKING open, which
     made the loss read as a bug. Capture before the page changes. */
  if (typeof scrView !== 'undefined' && scrView === 'form' && typeof captureScrHeader === 'function')
    captureScrHeader();
  page = pg;
  activeSidebarItem = pg;
  lastOpenedRecord = null;
  expandOwningDropdown(pg);
  /* Land in the channel you last used for THIS screen, or the one the journey
     says the stage belongs to. Carrying the previous page's channel across is
     what makes a walkthrough feel arbitrary — you approve on a phone, tap
     through to the challan, and are still holding a phone for a Finance
     screen that nobody uses on one. */
  channel = channelForPage(pg);
  resetFilters();          /* F09 — filters never follow you to another page */
  if (withFilter && withFilter.length === 2)
    pageFilters()['flt-' + statusClass(withFilter[0])] = withFilter[1];
  renderPage();
  syncUrl();
}

/* Route an identifier to whichever module owns it, by its prefix. Used by the
   ?open= deep link and by cross-references between screens. */
/* Every document in the journey belongs to exactly one deal. Mapping back to
   it is what lets the journey bar follow whatever you just opened. */
function dealIdOf(id) {
  const r = (typeof scr === 'function' && scr(id)) ||
            (typeof po === 'function' && po(id)) ||
            (typeof shipment === 'function' && shipment(id)) ||
            (typeof dnote === 'function' && dnote(id)) ||
            (typeof challan === 'function' && challan(id)) ||
            (typeof imr === 'function' && imr(id));
  if (!r) return null;
  return r.scrId || r.id || null;
}

function openRecord(id) {
  const go = (pg, fn) => {
    if (!can(pg, 'v')) { toast('Your position cannot open ' + id + '.', 'bad'); return; }
    page = pg; activeSidebarItem = pg; lastOpenedRecord = id;
    /* THE BAR FOLLOWS WHAT YOU OPENED. Without this it kept narrating whatever
       deal it had picked for itself, so the header could describe SUB-000318
       while the record on screen was SUB-000319 — two unrelated stories on one
       page, which is exactly the incoherence the bar exists to remove. */
    const deal = dealIdOf(id);
    if (deal) trackDeal(deal);
    expandOwningDropdown(pg);
    /* Same rule as navigatePage: web unless a decision is waiting for this
       person on the screen the record opens onto. */
    channel = channelForPage(pg);
    fn(); renderPage(); syncUrl();
  };
  if (typeof scr === 'function' && scr(id))        return go('scr',            () => { scrSelected = id; scrView = 'detail'; });
  if (typeof po === 'function' && po(id))          return go('orders',         () => { poSelected = id; poView = 'detail'; });
  if (typeof shipment === 'function' && shipment(id)) return go('shipments',   () => { shipSelected = id; shipView = 'detail'; });
  if (typeof dnote === 'function' && dnote(id))    return go('delivery-notes', () => { dnSelected = id; });
  if (typeof challan === 'function' && challan(id))return go('challans',       () => { chSelected = id; });
  /* An IMR opens its parent challan — that is where its receipts are listed. */
  if (typeof imr === 'function' && imr(id))
    return go('inward', () => { inwSelected = imr(id).challanId; });
  toast('There is no screen for ' + id + '.', 'bad');
}

/* True when openRecord would actually go somewhere. refLink asks first, so a
   dead identifier is never dressed up as a button that silently does nothing. */
function isRoutable(id) {
  if (!id) return false;
  return !!((typeof scr === 'function' && scr(id)) ||
            (typeof po === 'function' && po(id)) ||
            (typeof shipment === 'function' && shipment(id)) ||
            (typeof dnote === 'function' && dnote(id)) ||
            (typeof challan === 'function' && challan(id)) ||
            (typeof imr === 'function' && imr(id)));
}

/* ── Custom select ──────────────────────────────────────────────────────────
   Carried over from ADT.  Fixed-position menu, because every one of these
   opens inside an overflow:auto container that would clip an absolute one. */
/* WHETHER A FIELD IS SET IS TRACKED, NOT GUESSED.

   This used to derive "unset" by comparing the displayed text to the
   placeholder — so any real value that happened to equal its own placeholder
   was treated as empty. That was not cosmetic. Two live faults came out of it:

     · The order form passes taxCode 'GST 18%' with placeholder 'GST 18%', so
       getSelectValue() returned '' and capturePo() wiped the tax code on every
       save.
     · The logistics form passes mode 'Road' with placeholder 'Road', so the
       mode read back as '' and MODE_REQUIRED[''] was undefined — the entire
       mode-driven mandatory-field rule was skipped, and a shipment could be
       dispatched with no vehicle, driver or transporter at all.

   `data-unset` now records the fact explicitly, and the placeholder styling
   follows from it rather than from a string comparison. */
/* `onChange` names a global called with (value, id) the moment an option is
   picked. selectCustomOption has honoured data-onchange from the start — but
   no form ever set it, so every dependent-field relationship in the app
   (vendor → rate contracts, transport mode → required fields, reason →
   mandatory remarks) was inert until something else forced a repaint. This
   sixth parameter is what finally wires them. */
function customSelect(id, selected, options, placeholder, variant, onChange) {
  const safeId = String(id).replace(/[^a-zA-Z0-9_-]/g, '-');
  const opts = (options || []).map(o => String(o));
  const hasValue = selected != null && String(selected) !== '';
  const current = hasValue ? String(selected) : (placeholder || opts[0] || 'Select');
  const optHtml = opts.map(o =>
    '<button type="button" class="custom-select-option ' + (hasValue && o === current ? 'selected' : '') +
    '" data-value="' + attrSafe(o) + '" onclick="selectCustomOption(event,this)">' +
    '<span class="custom-select-text">' + esc(o) + '</span>' +
    '<span class="custom-select-check">&#10003;</span></button>').join('');
  return '<div class="custom-select ' + (variant || '') + '" id="' + safeId + '"' +
    ' data-value="' + attrSafe(hasValue ? current : '') + '"' +
    ' data-unset="' + (hasValue ? '0' : '1') + '"' +
    (onChange ? ' data-onchange="' + attrSafe(onChange) + '"' : '') + '>' +
    '<button type="button" class="custom-select-trigger" onclick="toggleCustomSelect(event,\'' + safeId + '\')">' +
    '<span class="' + (hasValue ? '' : 'placeholder') + '">' + esc(current) + '</span>' +
    '<svg class="custom-select-chevron" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4"><polyline points="6 9 12 15 18 9"/></svg>' +
    '</button><div class="custom-select-menu">' + optHtml + '</div></div>';
}

function closeCustomSelects(exceptId) {
  document.querySelectorAll('.custom-select.open').forEach(s => {
    if (!exceptId || s.id !== exceptId) s.classList.remove('open');
  });
}

function toggleCustomSelect(event, id) {
  event.stopPropagation();
  const root = document.getElementById(id);
  if (!root) return;
  const open = root.classList.contains('open');
  closeCustomSelects(id);
  root.classList.toggle('open', !open);
  if (!open) {
    const trigger = root.querySelector('.custom-select-trigger');
    const menu = root.querySelector('.custom-select-menu');
    if (trigger && menu) {
      const r = trigger.getBoundingClientRect();
      placeAnchoredMenu(menu, r, { alignLeft: true, width: r.width });
    }
  }
}

function selectCustomOption(event, opt) {
  event.stopPropagation();
  const root = opt.closest('.custom-select');
  if (!root) return;
  const label = opt.querySelector('.custom-select-text');
  const trigger = root.querySelector('.custom-select-trigger span');
  root.dataset.value = label ? label.textContent.trim() : opt.textContent.trim();
  root.dataset.unset = '0';                       /* picking anything sets it */
  if (trigger && label) { trigger.innerHTML = label.innerHTML; trigger.classList.remove('placeholder'); }
  root.querySelectorAll('.custom-select-option').forEach(o => o.classList.remove('selected'));
  opt.classList.add('selected');
  root.classList.remove('open');
  if (root.dataset.onchange && typeof window[root.dataset.onchange] === 'function')
    window[root.dataset.onchange](root.dataset.value, root.id);
}

function getSelectValue(id) {
  const root = document.getElementById(id);
  if (!root) return '';
  if (root.dataset.unset === '1') return '';      /* the fact, not a guess */
  return root.dataset.value || '';
}

/* ── Anchored menu placement ────────────────────────────────────────────────
   Below if it fits, above if THAT fits, otherwise the roomier side with the
   height capped so the menu scrolls instead of leaving the viewport.  The
   ceiling is the bottom of the topbar, not the window: a menu that climbs over
   the bar covers the account switcher and reads as a panel belonging to
   nothing. */
const MENU_GAP = 6, MENU_EDGE = 10;

function fixedOrigin(el) {
  for (let p = el && el.parentElement; p && p !== document.documentElement; p = p.parentElement) {
    const cs = window.getComputedStyle(p);
    if ((cs.transform && cs.transform !== 'none') ||
        (cs.perspective && cs.perspective !== 'none') ||
        (cs.filter && cs.filter !== 'none') ||
        /transform|perspective|filter/.test(cs.willChange || '') ||
        /paint|layout|strict|content/.test(cs.contain || '')) {
      const r = p.getBoundingClientRect();
      return { x: r.left, y: r.top };
    }
  }
  return { x: 0, y: 0 };
}

function menuBounds() {
  let top = MENU_EDGE;
  const bar = document.querySelector('.topbar');
  if (bar) {
    const r = bar.getBoundingClientRect();
    if (r.height && r.bottom > 0) top = r.bottom + MENU_GAP;
  }
  return { top: top, bottom: window.innerHeight - MENU_EDGE };
}

function placeAnchoredMenu(menu, anchor, opts) {
  if (!menu || !anchor) return;
  opts = opts || {};
  menu.style.maxHeight = ''; menu.style.right = 'auto'; menu.style.bottom = 'auto';
  menu.style.top = '0px'; menu.style.left = '0px';
  if (opts.width) menu.style.width = opts.width + 'px';
  const mw = menu.offsetWidth, mh = menu.offsetHeight;
  const vw = window.innerWidth;

  let left = opts.alignLeft ? anchor.left : anchor.right - mw;
  left = Math.min(Math.max(MENU_EDGE, left), Math.max(MENU_EDGE, vw - mw - MENU_EDGE));

  const b = menuBounds();
  const below = b.bottom - anchor.bottom - MENU_GAP;
  const above = anchor.top - MENU_GAP - b.top;
  let top, cap;
  if (mh <= below)      { top = anchor.bottom + MENU_GAP; cap = below; }
  else if (mh <= above) { top = anchor.top - MENU_GAP - mh; cap = above; }
  else if (below >= above) { top = anchor.bottom + MENU_GAP; cap = below; }
  else                  { top = b.top; cap = above; }
  cap = Math.max(120, Math.min(cap, b.bottom - b.top));
  top = Math.min(Math.max(b.top, top), Math.max(b.top, b.bottom - Math.min(mh, cap)));

  const o = fixedOrigin(menu);
  menu.style.left = Math.round(left - o.x) + 'px';
  menu.style.top = Math.round(top - o.y) + 'px';
  menu.style.maxHeight = (cap < mh) ? Math.floor(cap) + 'px' : '';
  if (cap < mh) {
    const cur = menu.querySelector('.selected');
    menu.scrollTop = cur ? Math.max(0, cur.offsetTop - (cap - cur.offsetHeight) / 2) : 0;
  } else menu.scrollTop = 0;
}

/* A fixed menu does not travel with the thing it is anchored to, so closing is
   the honest response to a scroll.  A scroll that STARTED inside an open menu
   is the user reading it, and is ignored. */
function closeAnchoredMenus(e) {
  const t = e && e.target;
  if (t && t.closest && t.closest('.custom-select-menu, .hdr-dd-panel')) return;
  closeCustomSelects();
  closeHeaderMenus();
}
window.addEventListener('scroll', closeAnchoredMenus, true);
window.addEventListener('resize', closeAnchoredMenus);
document.addEventListener('click', e => {
  if (!e.target.closest('.custom-select')) closeCustomSelects();
  if (!e.target.closest('.hdr-dd-wrap')) closeHeaderMenus();
});
document.addEventListener('keydown', e => {
  if (e.key === 'Escape') { closeCustomSelects(); closeHeaderMenus(); }
});

/* ── Header dropdowns and the role switcher ─────────────────────────────── */
function closeHeaderMenus(except) {
  document.querySelectorAll('.hdr-dd-panel.open').forEach(p => {
    if (!except || p.id !== except) p.classList.remove('open');
  });
}

function toggleHeaderMenu(id) {
  event.stopPropagation();
  const p = document.getElementById(id);
  if (!p) return;
  const open = p.classList.contains('open');
  closeHeaderMenus(id);
  p.classList.toggle('open', !open);
}

/* The switcher is what makes the per-Team decision visible: pick two users in
   the same Team and the nav is identical; pick two in different Teams and it
   changes.  Position is shown alongside because it still drives the special
   actions and the commercial mask. */
function buildRoleSwitcher() {
  const groups = {};
  Object.keys(USERS).forEach(id => {
    const u = USERS[id];
    if (!u.team) return;         /* external users are not internal roles */
    (groups[u.team] = groups[u.team] || []).push(id);
  });
  let html = '';
  Object.keys(groups).forEach(teamId => {
    const t = TEAMS[teamId];
    html += '<div class="rs-group"><div class="rs-group-head">' + esc(t.name) +
            '<span class="rs-code">' + esc(teamId) + '</span></div>';
    groups[teamId].forEach(id => {
      const u = USERS[id];
      html += '<button class="hdr-dd-item' + (id === currentUserId ? ' rs-current' : '') +
              '" onclick="closeHeaderMenus();setCurrentUser(\'' + id + '\')">' +
              '<span class="rs-avatar">' + esc(initials(u.name)) + '</span>' +
              '<span class="rs-who"><span class="rs-name">' + esc(u.name) + '</span>' +
              '<span class="rs-pos">' + esc(positionLabel(u.position)) + '</span></span></button>';
    });
    html += '</div>';
  });
  return html;
}

function renderTopbarUser() {
  const u = currentUser();
  const trigger = document.getElementById('user-trigger');
  if (trigger) {
    trigger.innerHTML = '<div class="user-avatar-sm">' + esc(initials(u.name)) + '</div>' +
      '<span class="tb-user-name">' + esc(u.name) + '</span>' +
      '<span class="tb-user-pos">' + esc(positionLabel(u.position)) + '</span>' +
      '<svg class="hdr-dd-chev" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="6 9 12 15 18 9"/></svg>';
  }
  const panel = document.getElementById('user-dd');
  if (panel) panel.innerHTML = '<div class="rs-head">Switch role</div>' + buildRoleSwitcher();
  const teamEl = document.getElementById('tb-team');
  if (teamEl) teamEl.textContent = currentTeam() ? currentTeam().name : '';

  /* The bell was decorative. It now carries this position's events — switching
     role changes the inbox, which is what makes the per-role model legible. */
  const notifPanel = document.getElementById('notif-dd');
  if (notifPanel && typeof buildNotifPanel === 'function') notifPanel.innerHTML = buildNotifPanel();
  const badge = document.getElementById('notif-badge');
  if (badge && typeof unreadCount === 'function') {
    const n = unreadCount(currentPosition());
    badge.hidden = n === 0;
    badge.textContent = n > 9 ? '9+' : String(n);
  }
}

/* ── Toast ──────────────────────────────────────────────────────────────────
   For confirmations only.  A blocked action explains itself where it was
   blocked, never in a toast that floats away before it is read. */
let toastTimer = null;
function toast(msg, tone) {
  const host = document.getElementById('toast-host');
  if (!host) return;
  /* A2 · role="status" + aria-live so a confirmation is announced rather than
     appearing silently for 3.6 seconds and vanishing. */
  host.innerHTML = '<div class="toast toast-' + (tone || 'ok') + '" role="status" aria-live="polite">' +
    '<span class="toast-msg">' + esc(msg) + '</span>' +
    '<button class="toast-close" onclick="dismissToast()" aria-label="Dismiss">&times;</button></div>';
  clearTimeout(toastTimer);
  toastTimer = setTimeout(dismissToast, 3600);
}
function dismissToast() {
  const host = document.getElementById('toast-host');
  if (host) host.innerHTML = '';
  clearTimeout(toastTimer);
}

/* ── Boot ───────────────────────────────────────────────────────────────── */
function boot() {
  /* ?as=u-security opens the app as that user. Deep-linking a role is what
     makes a demo walkthrough repeatable — you can hand someone a link to the
     exact queue you want them to look at instead of talking them through the
     switcher first. */
  const as = new URLSearchParams(location.search).get('as');

  /* Seeding runs as internal staff regardless of who is about to sign in, so
     the demo data is identical whichever role you open the app as. */
  if (typeof seedDemo === 'function') { currentUserId = 'u-planner'; seedDemo(); }
  if (as && USERS[as]) currentUserId = as;

  /* ?page=challans opens straight onto a screen. With ?as= this makes any
     point in the walkthrough a single link — which is what a demo script
     needs, and what makes each screen testable in isolation. */
  const pg = new URLSearchParams(location.search).get('page');
  if (pg && PAGE_TITLE[pg]) { page = pg; activeSidebarItem = pg; }

  /* ?open=SUB-000318 lands on a specific record's detail view. Together with
     ?as and ?page this makes every step of the walkthrough a single link. */
  const open = new URLSearchParams(location.search).get('open');
  if (open) openRecord(open);

  /* ?view=mobile opens the same screen on a phone. Part of the same demo-link
     set as ?as and ?page: "the approver's queue, as they see it" is a link,
     not three instructions.

     Applied LAST, after ?open has settled which screen we are on — otherwise
     it answers the question for the page named in the URL rather than the one
     the record actually opened. Without an explicit view the default is web,
     and only a decision waiting for this user opens a phone. */
  const vw = new URLSearchParams(location.search).get('view');
  channel = (vw === 'mobile' || vw === 'web') ? vw : channelForPage(page);

  renderTopbarUser();
  if (!can(page, 'v')) { page = firstAllowedPage(); activeSidebarItem = page; }
  /* F33 again, on the one route that was missed. Every other way into a child
     page — navigatePage, openRecord, openMobileTask, switchToStageActor —
     expands the dropdown that owns it. boot() did not, so ?page=delivery-notes
     landed with the active item inside a collapsed Documents group and nothing
     highlighted at all. That is the deep-link mechanism the whole demo script
     is built on. */
  expandOwningDropdown(page);
  buildSidebar();
  renderPage();
}
document.addEventListener('DOMContentLoaded', boot);
